import tkinter as tk
from tkinter import ttk, filedialog, messagebox, colorchooser
import numpy as np
import json
import datetime
import copy
import os
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.patches import Rectangle

# =============================================================================
# 模块1: 核心数据结构与辅助函数
# =============================================================================

class NumpyEncoder(json.JSONEncoder):
    """ Custom encoder for numpy data types """
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        return json.JSONEncoder.default(self, obj)

def create_new_design_object(suffix=None):
    """创建一个新的、空的design_object字典模板。"""
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    design_id = f"design_{timestamp}"
    if suffix is not None:
        design_id = f"{design_id}_{suffix}"
    return {
        "design_id": design_id,
        "metadata": {
            "process": "GF 22FDX+",
            "pixel_size_um": 14.0,
            "description": "Generated by LayoutGeneratorApp",
            "base_matrix_shape": [16, 16],
            "layers_used": [],
            "fill_ratio": 0.5,  # 默认填充率
            "actual_fill_ratio": 0.5  # 实际使用的填充率（批量生成时可能不同）
        },
        "layout_matrices": {},
        "port_definitions": []
    }

def generate_random_matrices(layers, shape=(16, 16), fill_ratio=0.5):
    """为指定的层生成随机的二进制矩阵。"""
    matrices = {}
    for layer in layers:
        matrices[layer] = (np.random.rand(*shape) < fill_ratio).astype(int)
    return matrices

def darken_color(hex_color, factor=0.7):
    """将一个HEX颜色变暗。"""
    if hex_color.startswith('#'):
        hex_color = hex_color[1:]
    rgb = tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    darker_rgb = tuple(int(c * factor) for c in rgb)
    return f"#{darker_rgb[0]:02x}{darker_rgb[1]:02x}{darker_rgb[2]:02x}"

# =============================================================================
# 模块2 & 3: 图形用户界面 (GUI) 应用
# =============================================================================

class LayoutGeneratorApp:
    def __init__(self, root):
        self.root = root
        self.root.title("RFIC布局数据生成器 V5 (超级增强版)")
        self.root.geometry("1300x850")

        self.design_objects_store = {}
        self.current_design = create_new_design_object()
        self.layer_colors = {}

        self.main_frame = ttk.Frame(self.root, padding="10")
        self.main_frame.pack(fill=tk.BOTH, expand=True)

        self.main_frame.grid_columnconfigure(0, weight=3, minsize=350)
        self.main_frame.grid_columnconfigure(1, weight=4, minsize=500)
        self.main_frame.grid_columnconfigure(2, weight=3, minsize=350)
        self.main_frame.grid_rowconfigure(0, weight=1)

        self._create_left_panel()
        self._create_middle_panel()
        self._create_right_panel()

        self._update_ui_from_design(self.current_design)

    def _create_left_panel(self):
        left_panel = ttk.LabelFrame(self.main_frame, text="控制与信息面板", padding="10")
        left_panel.grid(row=0, column=0, sticky="nsew", padx=5, pady=5)
        
        # --- 元数据区域 ---
        meta_frame = ttk.LabelFrame(left_panel, text="元数据 (Metadata)", padding="10")
        meta_frame.pack(fill=tk.X, expand=False, pady=5)
        self.meta_vars = {
            "Design ID": tk.StringVar(), "Process": tk.StringVar(value="GF 22FDX+"),
            "Pixel Size (um)": tk.StringVar(value="14.0"), "Description": tk.StringVar(value="Generated by App")
        }
        ttk.Label(meta_frame, text="Design ID:").grid(row=0, column=0, sticky="w")
        ttk.Label(meta_frame, textvariable=self.meta_vars["Design ID"]).grid(row=0, column=1, sticky="w")
        ttk.Label(meta_frame, text="Process:").grid(row=1, column=0, sticky="w")
        ttk.Entry(meta_frame, textvariable=self.meta_vars["Process"]).grid(row=1, column=1, sticky="ew")
        ttk.Label(meta_frame, text="Pixel Size (um):").grid(row=2, column=0, sticky="w")
        ttk.Entry(meta_frame, textvariable=self.meta_vars["Pixel Size (um)"]).grid(row=2, column=1, sticky="ew")
        ttk.Label(meta_frame, text="Description:").grid(row=3, column=0, sticky="w")
        ttk.Entry(meta_frame, textvariable=self.meta_vars["Description"]).grid(row=3, column=1, sticky="ew")

        # --- 层管理 ---
        layer_frame = ttk.LabelFrame(left_panel, text="层管理 (Layers)", padding="10")
        layer_frame.pack(fill=tk.X, expand=False, pady=5)
        self.layer_var = tk.StringVar()
        add_layer_frame = ttk.Frame(layer_frame)
        add_layer_frame.pack(fill=tk.X)
        ttk.Label(add_layer_frame, text="层名称:").pack(side=tk.LEFT, padx=5)
        ttk.Entry(add_layer_frame, textvariable=self.layer_var).pack(side=tk.LEFT, expand=True, fill=tk.X)
        ttk.Button(add_layer_frame, text="添加", command=self._add_layer).pack(side=tk.LEFT, padx=5)
        
        layer_list_frame = ttk.Frame(layer_frame)
        layer_list_frame.pack(fill=tk.X, expand=True, pady=5)
        self.layers_listbox = tk.Listbox(layer_list_frame, height=4)
        self.layers_listbox.pack(side=tk.LEFT, fill=tk.X, expand=True)
        layer_btn_frame = ttk.Frame(layer_list_frame)
        layer_btn_frame.pack(side=tk.LEFT, fill=tk.Y, padx=5)
        ttk.Button(layer_btn_frame, text="▲", command=lambda: self._move_item_in_list('layer', -1)).pack()
        ttk.Button(layer_btn_frame, text="▼", command=lambda: self._move_item_in_list('layer', 1)).pack()
        ttk.Button(layer_btn_frame, text="删", command=self._delete_layer).pack(pady=5)

        # --- 生成参数区域 ---
        param_frame = ttk.LabelFrame(left_panel, text="生成参数 (Generation Parameters)", padding="10")
        param_frame.pack(fill=tk.X, expand=False, pady=5)
        
        # 填充率控制
        fill_ratio_frame = ttk.Frame(param_frame)
        fill_ratio_frame.pack(fill=tk.X, pady=2)
        ttk.Label(fill_ratio_frame, text="填充率:").pack(side=tk.LEFT, padx=5)
        
        self.fill_ratio_var = tk.DoubleVar(value=0.5)
        self.fill_ratio_scale = ttk.Scale(fill_ratio_frame, from_=0.1, to=0.9, 
                                         variable=self.fill_ratio_var, orient=tk.HORIZONTAL)
        self.fill_ratio_scale.pack(side=tk.LEFT, expand=True, fill=tk.X, padx=5)
        
        self.fill_ratio_label = ttk.Label(fill_ratio_frame, text="0.50")
        self.fill_ratio_label.pack(side=tk.LEFT, padx=5)
        
        # 绑定滑块事件
        self.fill_ratio_scale.bind('<Motion>', self._update_fill_ratio_label)
        self.fill_ratio_scale.bind('<ButtonRelease-1>', self._update_fill_ratio_design)
        
        # 填充率说明
        ttk.Label(param_frame, text="范围: 0.1 (稀疏) - 0.9 (密集)", 
                 font=('TkDefaultFont', 8)).pack(pady=2)
        
        # --- 端口定义区域 ---
        port_frame = ttk.LabelFrame(left_panel, text="端口定义 (Port Definitions)", padding="10")
        port_frame.pack(fill=tk.BOTH, expand=True, pady=5)
        self.port_vars = {
            "ID": tk.StringVar(value="1"), "Name": tk.StringVar(value="P1"),
            "Layer": tk.StringVar(), "Edge": tk.StringVar(value="left"), "Index": tk.StringVar(value="8")
        }
        port_grid = ttk.Frame(port_frame)
        port_grid.pack(fill=tk.X)
        ttk.Label(port_grid, text="ID:").grid(row=0, column=0)
        ttk.Entry(port_grid, textvariable=self.port_vars["ID"], width=5).grid(row=0, column=1)
        ttk.Label(port_grid, text="Name:").grid(row=0, column=2)
        ttk.Entry(port_grid, textvariable=self.port_vars["Name"], width=8).grid(row=0, column=3)
        ttk.Label(port_grid, text="Layer:").grid(row=1, column=0)
        self.port_layer_menu = ttk.OptionMenu(port_grid, self.port_vars["Layer"], "N/A")
        self.port_layer_menu.grid(row=1, column=1, sticky="ew")
        ttk.Label(port_grid, text="Edge:").grid(row=1, column=2)
        ttk.OptionMenu(port_grid, self.port_vars["Edge"], "left", "left", "right", "top", "bottom").grid(row=1, column=3, sticky="ew")
        ttk.Label(port_grid, text="Index:").grid(row=2, column=0)
        ttk.Entry(port_grid, textvariable=self.port_vars["Index"], width=5).grid(row=2, column=1)
        port_crud_frame = ttk.Frame(port_grid)
        port_crud_frame.grid(row=2, column=2, columnspan=2, pady=5, sticky='e')
        ttk.Button(port_crud_frame, text="添加", command=self._add_port).pack(side=tk.LEFT)
        ttk.Button(port_crud_frame, text="更新", command=self._update_port).pack(side=tk.LEFT, padx=5)

        port_list_frame = ttk.Frame(port_frame)
        port_list_frame.pack(fill=tk.BOTH, expand=True, pady=5)
        self.ports_listbox = tk.Listbox(port_list_frame, height=6)
        self.ports_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        self.ports_listbox.bind('<<ListboxSelect>>', self._on_port_select)
        port_list_btn_frame = ttk.Frame(port_list_frame)
        port_list_btn_frame.pack(side=tk.LEFT, fill=tk.Y, padx=5)
        ttk.Button(port_list_btn_frame, text="▲", command=lambda: self._move_item_in_list('port', -1)).pack()
        ttk.Button(port_list_btn_frame, text="▼", command=lambda: self._move_item_in_list('port', 1)).pack()
        ttk.Button(port_list_btn_frame, text="删", command=self._delete_port).pack(pady=5)

    def _create_middle_panel(self):
        middle_panel = ttk.LabelFrame(self.main_frame, text="可视化预览", padding="10")
        middle_panel.grid(row=0, column=1, sticky="nsew", padx=5, pady=5)
        
        # Layer visibility control frame
        layer_ctrl_frame = ttk.Frame(middle_panel)
        layer_ctrl_frame.pack(side=tk.TOP, fill=tk.X, pady=5)
        
        self.layer_visibility_vars = {}
        self.all_layers_var = tk.BooleanVar(value=True)
        ttk.Checkbutton(layer_ctrl_frame, text="全部层", variable=self.all_layers_var, 
                       command=self._toggle_all_layers).pack(side=tk.LEFT, padx=5)
        
        self.layer_checkboxes_frame = ttk.Frame(layer_ctrl_frame)
        self.layer_checkboxes_frame.pack(side=tk.LEFT, fill=tk.X, expand=True)
        
        # Canvas for visualization
        self.fig = Figure(figsize=(6, 6), dpi=100)
        self.ax = self.fig.add_subplot(111)
        self.canvas = FigureCanvasTkAgg(self.fig, master=middle_panel)
        self.canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)
        self.canvas.draw()

    def _create_right_panel(self):
        right_panel = ttk.LabelFrame(self.main_frame, text="文件管理与操作", padding="10")
        right_panel.grid(row=0, column=2, sticky="nsew", padx=5, pady=5)
        
        list_frame = ttk.Frame(right_panel)
        list_frame.pack(fill=tk.BOTH, expand=True)
        self.design_listbox = tk.Listbox(list_frame, selectmode=tk.EXTENDED)
        self.design_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar = ttk.Scrollbar(list_frame, orient=tk.VERTICAL, command=self.design_listbox.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.design_listbox.config(yscrollcommand=scrollbar.set)
        self.design_listbox.bind('<<ListboxSelect>>', self._on_design_listbox_select)

        core_ops_frame = ttk.Frame(right_panel)
        core_ops_frame.pack(fill=tk.X, pady=10)
        ttk.Button(core_ops_frame, text="生成随机版图", command=self._generate_random).pack(fill=tk.X)
        ttk.Button(core_ops_frame, text="保存到列表", command=self._save_to_list).pack(fill=tk.X, pady=2)
        self.load_button = ttk.Button(core_ops_frame, text="从列表加载", command=self._load_from_list, state=tk.DISABLED)
        self.load_button.pack(fill=tk.X)
        self.save_json_button = ttk.Button(core_ops_frame, text="保存JSON到磁盘", command=self._save_json_to_disk, state=tk.DISABLED)
        self.save_json_button.pack(fill=tk.X, pady=2)
        self.batch_export_button = ttk.Button(core_ops_frame, text="批量导出选中", command=self._batch_export_to_disk, state=tk.DISABLED)
        self.batch_export_button.pack(fill=tk.X, pady=2)
        self.batch_import_button = ttk.Button(core_ops_frame, text="批量导入JSON", command=self._batch_import_from_disk)
        self.batch_import_button.pack(fill=tk.X, pady=2)

        batch_ops_frame = ttk.LabelFrame(right_panel, text="数据增强与批量操作", padding="10")
        batch_ops_frame.pack(fill=tk.X, pady=10)
        aug_frame = ttk.Frame(batch_ops_frame)
        aug_frame.pack(fill=tk.X)
        self.rot90_button = ttk.Button(aug_frame, text="旋转 90°", command=lambda: self._apply_transformation('rot90'), state=tk.DISABLED)
        self.rot90_button.pack(side=tk.LEFT, expand=True, fill=tk.X)
        self.rot180_button = ttk.Button(aug_frame, text="旋转 180°", command=lambda: self._apply_transformation('rot180'), state=tk.DISABLED)
        self.rot180_button.pack(side=tk.LEFT, expand=True, fill=tk.X)
        self.rot270_button = ttk.Button(aug_frame, text="旋转 270°", command=lambda: self._apply_transformation('rot270'), state=tk.DISABLED)
        self.rot270_button.pack(side=tk.LEFT, expand=True, fill=tk.X)
        flip_frame = ttk.Frame(batch_ops_frame)
        flip_frame.pack(fill=tk.X, pady=2)
        self.flip_lr_button = ttk.Button(flip_frame, text="水平翻转", command=lambda: self._apply_transformation('flip_lr'), state=tk.DISABLED)
        self.flip_lr_button.pack(side=tk.LEFT, expand=True, fill=tk.X)
        self.flip_ud_button = ttk.Button(flip_frame, text="垂直翻转", command=lambda: self._apply_transformation('flip_ud'), state=tk.DISABLED)
        self.flip_ud_button.pack(side=tk.LEFT, expand=True, fill=tk.X)
        
        # 批量生成区域（新增随机填充率控制）
        batch_gen_frame = ttk.Frame(batch_ops_frame)
        batch_gen_frame.pack(fill=tk.X, pady=5)
        
        # 数量输入
        count_frame = ttk.Frame(batch_gen_frame)
        count_frame.pack(fill=tk.X, pady=2)
        ttk.Label(count_frame, text="数量:").pack(side=tk.LEFT)
        self.batch_n_var = tk.StringVar(value="10")
        ttk.Entry(count_frame, textvariable=self.batch_n_var, width=5).pack(side=tk.LEFT)
        
        # 随机填充率选项
        self.random_fill_ratio_var = tk.BooleanVar(value=True)
        random_check = ttk.Checkbutton(count_frame, text="随机填充率", 
                                     variable=self.random_fill_ratio_var,
                                     command=self._toggle_random_fill_ratio_options)
        random_check.pack(side=tk.LEFT, padx=10)
        
        # 批量生成按钮
        ttk.Button(count_frame, text="批量生成", command=self._batch_generate).pack(side=tk.LEFT, expand=True, fill=tk.X, padx=5)
        
        # 随机填充率范围设置（动态显示）
        self.random_fill_options_frame = ttk.Frame(batch_gen_frame)
        self.random_fill_options_frame.pack(fill=tk.X, pady=2)
        
        range_frame = ttk.Frame(self.random_fill_options_frame)
        range_frame.pack(fill=tk.X)
        ttk.Label(range_frame, text="范围:").pack(side=tk.LEFT, padx=5)
        ttk.Label(range_frame, text="最小:").pack(side=tk.LEFT)
        self.fill_ratio_min_var = tk.StringVar(value="0.2")
        ttk.Entry(range_frame, textvariable=self.fill_ratio_min_var, width=5).pack(side=tk.LEFT)
        ttk.Label(range_frame, text="最大:").pack(side=tk.LEFT, padx=(5,0))
        self.fill_ratio_max_var = tk.StringVar(value="0.8")
        ttk.Entry(range_frame, textvariable=self.fill_ratio_max_var, width=5).pack(side=tk.LEFT)
        
        # 说明文本
        ttk.Label(self.random_fill_options_frame, text="随机填充率范围: 0.1-0.9", 
                 font=('TkDefaultFont', 8)).pack(pady=1)
        
        batch_del_frame = ttk.Frame(batch_ops_frame)
        batch_del_frame.pack(fill=tk.X, pady=5)
        self.delete_button = ttk.Button(batch_del_frame, text="删除选中", command=self._delete_selected, state=tk.DISABLED)
        self.delete_button.pack(side=tk.LEFT, expand=True, fill=tk.X)
        ttk.Button(batch_del_frame, text="全部清空", command=self._clear_all).pack(side=tk.LEFT, expand=True, fill=tk.X)

    def _toggle_random_fill_ratio_options(self):
        """切换随机填充率选项的显示"""
        if self.random_fill_ratio_var.get():
            self.random_fill_options_frame.pack(fill=tk.X, pady=2, after=self.batch_n_var.master.master)
        else:
            self.random_fill_options_frame.pack_forget()

    def _update_fill_ratio_label(self, event=None):
        """更新填充率标签显示"""
        ratio = self.fill_ratio_var.get()
        self.fill_ratio_label.config(text=f"{ratio:.2f}")

    def _update_fill_ratio_design(self, event=None):
        """更新当前设计的填充率"""
        if not self._gather_ui_data():
            return
        ratio = self.fill_ratio_var.get()
        self.current_design["metadata"]["fill_ratio"] = ratio
        self.current_design["metadata"]["actual_fill_ratio"] = ratio

    def _update_ui_from_design(self, design_obj):
        self.meta_vars["Design ID"].set(design_obj["design_id"])
        self.meta_vars["Process"].set(design_obj["metadata"].get("process", ""))
        self.meta_vars["Pixel Size (um)"].set(str(design_obj["metadata"].get("pixel_size_um", "")))
        self.meta_vars["Description"].set(design_obj["metadata"].get("description", ""))
        
        # 更新填充率显示
        fill_ratio = design_obj["metadata"].get("fill_ratio", 0.5)
        self.fill_ratio_var.set(fill_ratio)
        self._update_fill_ratio_label()
        
        self.layers_listbox.delete(0, tk.END)
        self.layer_colors = {}
        
        # Clear existing layer visibility checkboxes
        for widget in self.layer_checkboxes_frame.winfo_children():
            widget.destroy()
        self.layer_visibility_vars.clear()
        
        if len(design_obj["metadata"]["layers_used"]) > 0:
            colors = plt.get_cmap('viridis', len(design_obj["metadata"]["layers_used"]))
            for i, layer in enumerate(design_obj["metadata"]["layers_used"]):
                self.layers_listbox.insert(tk.END, layer)
                self.layer_colors[layer] = colors(i)
                
                # Add visibility checkbox
                var = tk.BooleanVar(value=True)
                self.layer_visibility_vars[layer] = var
                cb = ttk.Checkbutton(self.layer_checkboxes_frame, text=layer, variable=var,
                                   command=lambda: self.update_preview(self.current_design))
                cb.pack(side=tk.LEFT, padx=2)
        
        self._update_port_layer_options()

        self.ports_listbox.delete(0, tk.END)
        for port in design_obj["port_definitions"]:
            self.ports_listbox.insert(tk.END, f"ID:{port['port_id']} Name:{port['name']}")
        
        self.update_preview(design_obj)

    def _gather_ui_data(self):
        """从UI控件收集数据，更新到self.current_design。 Returns True on success, False on failure."""
        try:
            self.current_design["metadata"]["process"] = self.meta_vars["Process"].get()
            pixel_size_str = self.meta_vars["Pixel Size (um)"].get()
            self.current_design["metadata"]["pixel_size_um"] = float(pixel_size_str) if pixel_size_str else 0.0
            self.current_design["metadata"]["description"] = self.meta_vars["Description"].get()
            self.current_design["metadata"]["fill_ratio"] = self.fill_ratio_var.get()
            return True
        except ValueError:
            messagebox.showerror("输入错误", "Pixel Size (um) 必须是一个有效的数字。")
            return False

    def _add_layer(self):
        if not self._gather_ui_data(): return
        layer_name = self.layer_var.get().strip()
        if layer_name and layer_name not in self.current_design["metadata"]["layers_used"]:
            self.current_design["metadata"]["layers_used"].append(layer_name)
            self.current_design["layout_matrices"][layer_name] = np.zeros(self.current_design["metadata"]["base_matrix_shape"])
            self._update_ui_from_design(self.current_design)
            self.layer_var.set("")
    
    def _delete_layer(self):
        if not self._gather_ui_data(): return
        selected_indices = self.layers_listbox.curselection()
        if not selected_indices: return
        
        layer_name = self.layers_listbox.get(selected_indices[0])
        if messagebox.askyesno("确认", f"删除层 '{layer_name}' 将同时删除所有关联的端口。确定要继续吗？"):
            self.current_design["metadata"]["layers_used"].remove(layer_name)
            del self.current_design["layout_matrices"][layer_name]
            self.current_design["port_definitions"] = [p for p in self.current_design["port_definitions"] if p['layer'] != layer_name]
            self._update_ui_from_design(self.current_design)

    def _update_port_layer_options(self):
        menu = self.port_layer_menu["menu"]
        menu.delete(0, "end")
        layers = self.current_design["metadata"]["layers_used"]
        if not layers:
            menu.add_command(label="N/A", command=lambda: self.port_vars["Layer"].set("N/A"))
            self.port_vars["Layer"].set("N/A")
        else:
            for layer in layers:
                menu.add_command(label=layer, command=lambda value=layer: self.port_vars["Layer"].set(value))
            if self.port_vars["Layer"].get() not in layers:
                self.port_vars["Layer"].set(layers[0])

    def _add_port(self):
        if not self._gather_ui_data(): return
        try:
            port_def = { "port_id": int(self.port_vars["ID"].get()), "name": self.port_vars["Name"].get(), "layer": self.port_vars["Layer"].get(), "edge": self.port_vars["Edge"].get(), "position_index": int(self.port_vars["Index"].get()) }
            if port_def["layer"] == "N/A": messagebox.showerror("错误", "请先添加一个层。"); return
            if any(p['port_id'] == port_def['port_id'] for p in self.current_design["port_definitions"]): messagebox.showerror("错误", f"端口ID {port_def['port_id']} 已存在。"); return
            self.current_design["port_definitions"].append(port_def)
            self._update_ui_from_design(self.current_design)
            new_id = int(self.port_vars["ID"].get()) + 1
            self.port_vars["ID"].set(str(new_id))
            self.port_vars["Name"].set(f"P{new_id}")
        except ValueError: messagebox.showerror("错误", "端口ID和Index必须是整数。")

    def _update_port(self):
        if not self._gather_ui_data(): return
        selected_indices = self.ports_listbox.curselection()
        if not selected_indices: messagebox.showinfo("提示", "请先在列表中选择一个要更新的端口。"); return
        
        try:
            new_port_def = { "port_id": int(self.port_vars["ID"].get()), "name": self.port_vars["Name"].get(), "layer": self.port_vars["Layer"].get(), "edge": self.port_vars["Edge"].get(), "position_index": int(self.port_vars["Index"].get()) }
            original_port_id = self.current_design["port_definitions"][selected_indices[0]]['port_id']
            if new_port_def['port_id'] != original_port_id and any(p['port_id'] == new_port_def['port_id'] for p in self.current_design["port_definitions"]):
                messagebox.showerror("错误", f"端口ID {new_port_def['port_id']} 已被其他端口使用。"); return
            self.current_design["port_definitions"][selected_indices[0]] = new_port_def
            self._update_ui_from_design(self.current_design)
        except ValueError: messagebox.showerror("错误", "端口ID和Index必须是整数。")

    def _delete_port(self):
        if not self._gather_ui_data(): return
        selected_indices = self.ports_listbox.curselection()
        if not selected_indices: return
        for index in sorted(selected_indices, reverse=True):
            del self.current_design["port_definitions"][index]
        self._update_ui_from_design(self.current_design)

    def _on_port_select(self, event):
        selected_indices = self.ports_listbox.curselection()
        if not selected_indices: return
        port_data = self.current_design["port_definitions"][selected_indices[0]]
        self.port_vars["ID"].set(str(port_data["port_id"]))
        self.port_vars["Name"].set(port_data["name"])
        self.port_vars["Layer"].set(port_data["layer"])
        self.port_vars["Edge"].set(port_data["edge"])
        self.port_vars["Index"].set(str(port_data["position_index"]))

    def _move_item_in_list(self, list_type, direction):
        if not self._gather_ui_data(): return
        if list_type == 'layer':
            listbox = self.layers_listbox
            data_list = self.current_design["metadata"]["layers_used"]
        else:
            listbox = self.ports_listbox
            data_list = self.current_design["port_definitions"]
        selected_indices = listbox.curselection()
        if not selected_indices: return
        idx = selected_indices[0]
        if direction == -1 and idx > 0:
            data_list[idx], data_list[idx-1] = data_list[idx-1], data_list[idx]
            new_selection_idx = idx - 1
        elif direction == 1 and idx < len(data_list) - 1:
            data_list[idx], data_list[idx+1] = data_list[idx+1], data_list[idx]
            new_selection_idx = idx + 1
        else:
            return
        if list_type == 'layer':
            self.current_design["layout_matrices"] = {layer: self.current_design["layout_matrices"][layer] for layer in data_list}
        self._update_ui_from_design(self.current_design)
        listbox.selection_set(new_selection_idx)

    def _toggle_all_layers(self):
        """Toggle visibility of all layers."""
        all_checked = self.all_layers_var.get()
        for var in self.layer_visibility_vars.values():
            var.set(all_checked)
        self.update_preview(self.current_design)

    def update_preview(self, design_obj):
        self.ax.clear()
        N = design_obj["metadata"]["base_matrix_shape"][0]
        grid_size = N + 2
        self.ax.add_patch(Rectangle((0, 0), grid_size, grid_size, facecolor='lightgrey', edgecolor='black', hatch='//', alpha=0.3))
        self.ax.add_patch(Rectangle((1, 1), N, N, facecolor='white', edgecolor='black'))
        legend_patches = []
        
        # Check if we should respect layer visibility
        use_layer_visibility = hasattr(self, 'layer_visibility_vars') and self.layer_visibility_vars
        
        for layer_name in design_obj["metadata"]["layers_used"]:
            # Skip if layer is not visible
            if use_layer_visibility and not self.layer_visibility_vars.get(layer_name, tk.BooleanVar(value=True)).get():
                continue
                
            matrix = design_obj["layout_matrices"].get(layer_name)
            if matrix is None: continue
            color = self.layer_colors.get(layer_name, (0.5,0.5,0.5,1.0))
            for r in range(N):
                for c in range(N):
                    if matrix[r, c] == 1:
                        y_coord = (N - 1 - r) + 1
                        self.ax.add_patch(Rectangle((c + 1, y_coord), 1, 1, facecolor=color, alpha=0.6))
            legend_patches.append(Rectangle((0, 0), 1, 1, facecolor=color, alpha=0.6, label=layer_name))
        
        for port in design_obj["port_definitions"]:
            # Skip port if its layer is not visible
            if use_layer_visibility and not self.layer_visibility_vars.get(port["layer"], tk.BooleanVar(value=True)).get():
                continue
                
            color = self.layer_colors.get(port["layer"], (0.5,0.5,0.5,1.0))
            port_color = darken_color(matplotlib.colors.to_hex(color))
            edge, index = port["edge"], port["position_index"]
            if edge == "left": x, y = 0, (N - 1 - index) + 1
            elif edge == "right": x, y = N + 1, (N - 1 - index) + 1
            elif edge == "bottom": x, y = index + 1, 0
            elif edge == "top": x, y = index + 1, N + 1
            else: continue
            self.ax.add_patch(Rectangle((x, y), 1, 1, facecolor=port_color, edgecolor='black'))
            self.ax.text(x + 0.5, y + 0.5, f"{port['port_id']}", ha='center', va='center', fontsize=8, color='white', weight='bold')
        self.ax.set_xticks(np.arange(0, grid_size + 1, 1)); self.ax.set_yticks(np.arange(0, grid_size + 1, 1))
        self.ax.grid(True, which='both', color='black', linewidth=0.5)
        self.ax.set_xlim(0, grid_size); self.ax.set_ylim(0, grid_size)
        self.ax.set_aspect('equal', adjustable='box')
        self.ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)
        if legend_patches: self.ax.legend(handles=legend_patches, bbox_to_anchor=(1.05, 1), loc='upper left')
        self.fig.tight_layout(rect=[0, 0, 0.85, 1])
        self.canvas.draw()

    def _on_design_listbox_select(self, event):
        selected_indices = self.design_listbox.curselection()
        num_selected = len(selected_indices)
        
        # Handle single selection for loading
        if num_selected == 1:
            self.load_button.config(state=tk.NORMAL)
            self.save_json_button.config(state=tk.NORMAL)
            self._load_from_list()
        else:
            self.load_button.config(state=tk.DISABLED)
            self.save_json_button.config(state=tk.NORMAL if num_selected >= 1 else tk.DISABLED)
        
        # Handle all transformation buttons
        button_state = tk.NORMAL if num_selected > 0 else tk.DISABLED
        self.delete_button.config(state=button_state)
        self.batch_export_button.config(state=button_state)
        
        # Transformation buttons
        self.rot90_button.config(state=button_state)
        self.rot180_button.config(state=button_state)
        self.rot270_button.config(state=button_state)
        self.flip_lr_button.config(state=button_state)
        self.flip_ud_button.config(state=button_state)

    def _generate_random(self):
        if not self._gather_ui_data(): return
        design = self.current_design
        layers = design["metadata"]["layers_used"]
        if not layers: messagebox.showerror("错误", "请至少添加一个层。"); return
        
        # 使用当前设置的填充率
        fill_ratio = design["metadata"]["fill_ratio"]
        self.current_design["layout_matrices"] = generate_random_matrices(layers, fill_ratio=fill_ratio)
        self.current_design["metadata"]["actual_fill_ratio"] = fill_ratio
        self.update_preview(self.current_design)

    def _save_to_list(self):
        if not self._gather_ui_data(): return
        design_to_save = copy.deepcopy(self.current_design)
        design_id = design_to_save["design_id"]
        if design_id in self.design_objects_store and not messagebox.askyesno("确认", f"ID '{design_id}' 已存在。要覆盖它吗？"): return
        self.design_objects_store[design_id] = design_to_save
        if design_id not in self.design_listbox.get(0, tk.END): self.design_listbox.insert(tk.END, design_id)
        self.current_design = create_new_design_object()
        self._update_ui_from_design(self.current_design)

    def _load_from_list(self):
        selected_indices = self.design_listbox.curselection()
        if not selected_indices: return
        selected_id = self.design_listbox.get(selected_indices[0])
        if selected_id in self.design_objects_store:
            self.current_design = copy.deepcopy(self.design_objects_store[selected_id])
            self._update_ui_from_design(self.current_design)

    def _save_json_to_disk(self):
        selected_indices = self.design_listbox.curselection()
        if not selected_indices or len(selected_indices) > 1: return
        selected_id = self.design_listbox.get(selected_indices[0])
        design_to_save = self.design_objects_store.get(selected_id)
        if design_to_save:
            filepath = filedialog.asksaveasfilename(defaultextension=".json", filetypes=[("JSON files", "*.json")], initialfile=f"{selected_id}.json")
            if filepath:
                with open(filepath, 'w') as f: json.dump(design_to_save, f, cls=NumpyEncoder, indent=4)
                messagebox.showinfo("成功", f"文件已保存到:\n{filepath}")

    def _apply_transformation(self, transform_type):
        selected_indices = self.design_listbox.curselection()
        if not selected_indices: return
        new_designs = {}
        for index in selected_indices:
            design_id = self.design_listbox.get(index)
            original_design = self.design_objects_store[design_id]
            new_design = copy.deepcopy(original_design)
            for layer, matrix in new_design["layout_matrices"].items():
                if transform_type == 'rot90':
                    new_design["layout_matrices"][layer] = np.rot90(matrix)
                    suffix = "_rot90"
                elif transform_type == 'rot180':
                    new_design["layout_matrices"][layer] = np.rot90(matrix, 2)
                    suffix = "_rot180"
                elif transform_type == 'rot270':
                    new_design["layout_matrices"][layer] = np.rot90(matrix, 3)
                    suffix = "_rot270"
                elif transform_type == 'flip_lr':
                    new_design["layout_matrices"][layer] = np.fliplr(matrix)
                    suffix = "_fliplr"
                elif transform_type == 'flip_ud':
                    new_design["layout_matrices"][layer] = np.flipud(matrix)
                    suffix = "_flipud"
            new_id = f"{design_id}{suffix}"; i = 1
            while new_id in self.design_objects_store or new_id in new_designs: new_id = f"{design_id}{suffix}_{i}"; i += 1
            new_design["design_id"] = new_id
            new_designs[new_id] = new_design
        for new_id, design in new_designs.items():
            self.design_objects_store[new_id] = design
            self.design_listbox.insert(tk.END, new_id)

    def _validate_fill_ratio_range(self):
        """验证填充率范围设置"""
        try:
            min_val = float(self.fill_ratio_min_var.get())
            max_val = float(self.fill_ratio_max_var.get())
            
            # 检查范围
            if min_val < 0.1 or min_val > 0.9:
                messagebox.showerror("错误", "最小填充率必须在0.1-0.9之间")
                return False
            if max_val < 0.1 or max_val > 0.9:
                messagebox.showerror("错误", "最大填充率必须在0.1-0.9之间")
                return False
            if min_val > max_val:
                messagebox.showerror("错误", "最小填充率不能大于最大填充率")
                return False
            
            return True
        except ValueError:
            messagebox.showerror("错误", "请输入有效的数字")
            return False

    def _batch_generate(self):
        """批量生成设计，支持随机填充率"""
        try:
            n = int(self.batch_n_var.get())
        except ValueError:
            messagebox.showerror("错误", "请输入一个有效的整数。")
            return
        
        if not self._gather_ui_data():
            return
        
        template_design = self.current_design
        layers = template_design["metadata"]["layers_used"]
        if not layers:
            messagebox.showerror("错误", "请至少添加一个层用于生成。")
            return
        
        # 检查是否使用随机填充率
        if self.random_fill_ratio_var.get():
            # 验证填充率范围
            if not self._validate_fill_ratio_range():
                return
            
            min_ratio = float(self.fill_ratio_min_var.get())
            max_ratio = float(self.fill_ratio_max_var.get())
            
            # 显示确认信息
            confirm_msg = f"将生成 {n} 个设计，每个设计使用随机的填充率（{min_ratio:.2f}-{max_ratio:.2f}）"
            if not messagebox.askyesno("确认批量生成", confirm_msg):
                return
        else:
            # 使用固定填充率
            fixed_ratio = template_design["metadata"]["fill_ratio"]
            confirm_msg = f"将生成 {n} 个设计，每个设计使用固定的填充率（{fixed_ratio:.2f}）"
            if not messagebox.askyesno("确认批量生成", confirm_msg):
                return
        
        # Get base timestamp for this batch
        base_timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        
        for i in range(n):
            new_design = copy.deepcopy(template_design)
            new_design["design_id"] = f"design_{base_timestamp}_{i}"
            
            # 确定填充率
            if self.random_fill_ratio_var.get():
                # 生成随机填充率
                actual_fill_ratio = np.random.uniform(min_ratio, max_ratio)
            else:
                # 使用固定填充率
                actual_fill_ratio = template_design["metadata"]["fill_ratio"]
            
            new_design["metadata"]["fill_ratio"] = template_design["metadata"]["fill_ratio"]
            new_design["metadata"]["actual_fill_ratio"] = actual_fill_ratio
            new_design["layout_matrices"] = generate_random_matrices(layers, fill_ratio=actual_fill_ratio)
            
            self.design_objects_store[new_design["design_id"]] = new_design
            self.design_listbox.insert(tk.END, new_design["design_id"])
        
        # 显示完成信息
        if self.random_fill_ratio_var.get():
            info_msg = f"已成功生成并添加 {n} 组新数据。\n每个设计使用随机填充率（{min_ratio:.2f}-{max_ratio:.2f}）。"
        else:
            info_msg = f"已成功生成并添加 {n} 组新数据。\n所有设计使用固定填充率（{fixed_ratio:.2f}）。"
        
        messagebox.showinfo("完成", info_msg)

    def _delete_selected(self):
        selected_indices = self.design_listbox.curselection()
        if not selected_indices: return
        selected_ids = [self.design_listbox.get(i) for i in selected_indices]
        if messagebox.askyesno("确认删除", f"您确定要删除选中的 {len(selected_ids)} 项吗？"):
            for design_id in selected_ids: del self.design_objects_store[design_id]
            for index in sorted(selected_indices, reverse=True): self.design_listbox.delete(index)
            self._on_design_listbox_select(None)

    def _batch_export_to_disk(self):
        selected_indices = self.design_listbox.curselection()
        if not selected_indices:
            messagebox.showwarning("提示", "请先选择要导出的设计。")
            return
        
        selected_ids = [self.design_listbox.get(i) for i in selected_indices]
        
        # Ask for export directory
        export_dir = filedialog.askdirectory(title="选择导出目录")
        if not export_dir:
            return
        
        exported_count = 0
        for design_id in selected_ids:
            design_to_save = self.design_objects_store.get(design_id)
            if design_to_save:
                filepath = os.path.join(export_dir, f"{design_id}.json")
                try:
                    with open(filepath, 'w') as f:
                        json.dump(design_to_save, f, cls=NumpyEncoder, indent=4)
                    exported_count += 1
                except Exception as e:
                    messagebox.showerror("导出错误", f"导出 {design_id} 时出错:\n{str(e)}")
                    return
        
        messagebox.showinfo("完成", f"成功导出 {exported_count} 个设计到:\n{export_dir}")

    def _batch_import_from_disk(self):
        """Batch import JSON files from filesystem (supports Linux and Windows)"""
        file_paths = filedialog.askopenfilenames(
            title="选择JSON文件导入",
            filetypes=[("JSON files", "*.json"), ("All files", "*.*")],
            initialdir=os.getcwd()
        )
        
        if not file_paths:
            return
        
        imported_count = 0
        failed_files = []
        
        for filepath in file_paths:
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    design_data = json.load(f)
                
                # Validate basic structure
                if not isinstance(design_data, dict):
                    failed_files.append(f"{os.path.basename(filepath)}: 无效的数据格式")
                    continue
                
                # Ensure required fields exist
                if "design_id" not in design_data:
                    design_data["design_id"] = f"imported_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')}"
                
                # Handle potential duplicate design IDs
                original_id = design_data["design_id"]
                counter = 1
                while design_data["design_id"] in self.design_objects_store:
                    design_data["design_id"] = f"{original_id}_{counter}"
                    counter += 1
                
                # Convert lists back to numpy arrays
                if "layout_matrices" in design_data:
                    for layer, matrix in design_data["layout_matrices"].items():
                        if isinstance(matrix, list):
                            design_data["layout_matrices"][layer] = np.array(matrix)
                
                # 确保有必要的字段，兼容旧版本
                if "metadata" in design_data:
                    if "fill_ratio" not in design_data["metadata"]:
                        design_data["metadata"]["fill_ratio"] = 0.5
                    if "actual_fill_ratio" not in design_data["metadata"]:
                        design_data["metadata"]["actual_fill_ratio"] = design_data["metadata"]["fill_ratio"]
                
                self.design_objects_store[design_data["design_id"]] = design_data
                self.design_listbox.insert(tk.END, design_data["design_id"])
                imported_count += 1
                
            except json.JSONDecodeError:
                failed_files.append(f"{os.path.basename(filepath)}: JSON格式错误")
            except Exception as e:
                failed_files.append(f"{os.path.basename(filepath)}: {str(e)}")
        
        if failed_files:
            messagebox.showwarning("导入警告", f"以下文件导入失败:\n" + "\n".join(failed_files))
        
        messagebox.showinfo("导入完成", f"成功导入 {imported_count} 个设计\n失败: {len(failed_files)} 个")

    def _clear_all(self):
        if messagebox.askyesno("确认清空", "您确定要清空列表中的所有数据吗？此操作无法撤销。"):
            self.design_objects_store.clear()
            self.design_listbox.delete(0, tk.END)
            self.current_design = create_new_design_object()
            self._update_ui_from_design(self.current_design)
            self._on_design_listbox_select(None)

if __name__ == "__main__":
    root = tk.Tk()
    app = LayoutGeneratorApp(root)
    root.mainloop()